version: "3.8"

services:
  leyline_api:
    build: .
    image: leyline-api
    container_name: leyline-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://leyline_user:password@db:5432/leyline_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    command:
      [
        "/wait-for-it.sh",
        "db:5432",
        "--",
        "/wait-for-it.sh",
        "redis:6379",
        "--",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "3000",
        "--log-level",
        "info",
      ]

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: leyline_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leyline_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
