global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "leyline-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["leyline-api:3000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
