# prometheus.yml
global:
  scrape_interval: 15s # Scrape targets every 15 seconds

scrape_configs:
  - job_name: "leyline"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:3000"]
